name: Front tests & reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: front
        run: npm install
      
      - name: Run tests and generate code coverage
        run: jest --ci --coverage
        working-directory: front

      - name: Upload Karma report artifact
        uses: actions/upload-artifact@v3
        with:
          name: Karma-report
          path: front/coverage